<?php

/**
 * SortableArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SortableArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SortableArticleTable
     */
    public static function getInstance()
    {
        return Doctrine::getTable('SortableArticle');
    }
}