<?php

/**
 * SortableArticleCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SortableArticleCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SortableArticleCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine::getTable('SortableArticleCategory');
    }
}