<?php

/**
 * BaseSortableArticleUniqueBy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $category_id
 * @property SortableArticleCategory $Category
 * 
 * @method string                  getName()        Returns the current record's "name" value
 * @method integer                 getCategoryId()  Returns the current record's "category_id" value
 * @method SortableArticleCategory getCategory()    Returns the current record's "Category" value
 * @method SortableArticleUniqueBy setName()        Sets the current record's "name" value
 * @method SortableArticleUniqueBy setCategoryId()  Sets the current record's "category_id" value
 * @method SortableArticleUniqueBy setCategory()    Sets the current record's "Category" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSortableArticleUniqueBy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_unique_by');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SortableArticleCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->actAs($sortable0);
    }
}