<?php

/**
 * BaseSortableArticleUniqueBy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $category
 * 
 * @method string                  getName()     Returns the current record's "name" value
 * @method string                  getCategory() Returns the current record's "category" value
 * @method SortableArticleUniqueBy setName()     Sets the current record's "name" value
 * @method SortableArticleUniqueBy setCategory() Sets the current record's "category" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSortableArticleUniqueBy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_unique_by');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'category',
             ),
             ));
        $this->actAs($sortable0);
    }
}