<?php

/**
 * BaseSortableArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string          getName() Returns the current record's "name" value
 * @method SortableArticle setName() Sets the current record's "name" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSortableArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sortable_article');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sortable0);
    }
}