<?php

/**
 * BaseSortableArticleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $SortableArticleUniqueBy
 * 
 * @method integer                 getId()                      Returns the current record's "id" value
 * @method string                  getName()                    Returns the current record's "name" value
 * @method Doctrine_Collection     getSortableArticleUniqueBy() Returns the current record's "SortableArticleUniqueBy" collection
 * @method SortableArticleCategory setId()                      Sets the current record's "id" value
 * @method SortableArticleCategory setName()                    Sets the current record's "name" value
 * @method SortableArticleCategory setSortableArticleUniqueBy() Sets the current record's "SortableArticleUniqueBy" collection
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSortableArticleCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sortable_article_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SortableArticleUniqueBy', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}